core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('survey_service.urls')),
    path('', include('django.contrib.auth.urls')),
]

survey_service/urls.py
from django.urls import path
from . import views


app_name = 'survey_service'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('register/', views.RegistrationFormView.as_view(), name='register'),
    path('surveys/', views.SurveyListView.as_view(), name='all_surveys'),
    path('survey/<int:pk>/', views.SurveyDetailView.as_view(), name='detail_survey'),
    path('survey_passed', views.SurveyPassedView.as_view(), name='survey_passed'),
    path('survey_failed', views.SurveyFailedView.as_view(), name='survey_failed'),
    path('profiles', views.ProfileListView.as_view(), name='profile_list'),
    path('profile/<int:pk>/', views.ProfileDetailView.as_view(), name='profile'),
    path('colors/', views.ColorListView.as_view(), name='colors'),
    path('buy_color/<int:pk>/', views.BuyColorView.as_view(), name='buy_color'),
    path('buy_failed/', views.BuyFailedView.as_view(), name='buy_failed'),
]

survey_service/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    currency = models.PositiveIntegerField(default=0, blank=True, verbose_name='currency')
    passed_surveys = models.ManyToManyField('Survey', blank=True, verbose_name='passed survey')
    color = models.CharField(max_length=50, default='green', blank=True, verbose_name='color')
    # user_colors для того, что бы уже купленный цвет сохранялся у пользователя
    # и можно было бы сделать метод update и там их менять
    user_colors = models.ManyToManyField('Color', blank=True, verbose_name='user color list')


class Color(models.Model):
    COLOR_CHOICES = [
        ('Pink', 'pink'),
        ('Blue', 'blue'),
        ('White', 'white'),
        ('Yellow', 'yellow'),
        ('Black', 'black'),
    ]
    color = models.CharField(choices=COLOR_CHOICES, max_length=25, verbose_name='color')
    price = models.PositiveIntegerField(verbose_name='price')

    def __str__(self):
        return self.color


class Survey(models.Model):
    title = models.CharField(max_length=150)
    description = models.CharField(max_length=500, blank=True)
    point = models.PositiveSmallIntegerField(default=1)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Survey'
        verbose_name_plural = 'Survey'


class Question(models.Model):
    text = models.CharField(max_length=400)
    survey = models.ForeignKey(Survey, on_delete=models.PROTECT)

    def __str__(self):
        return self.text

    class Meta:
        verbose_name = 'Question'
        verbose_name_plural = 'Questions'


class Answer(models.Model):
    text = models.CharField(max_length=200)
    question = models.ForeignKey(Question, on_delete=models.PROTECT)
    correct = models.BooleanField(default=False)

    def __str__(self):
        return self.text

    class Meta:
        verbose_name = 'Answer'
        verbose_name_plural = 'Answers'

survey_service/forms.py
from django import forms
from django.contrib.auth import get_user_model
from .models import Survey, Answer, Question, Color

User = get_user_model()


class RegistrationUserForm(forms.ModelForm):
    password_1 = forms.CharField(widget=forms.PasswordInput(), label='Введите пароль')
    password_2 = forms.CharField(widget=forms.PasswordInput(), label='Повторите пароль')

    def clean(self):
        cleaned_data = super().clean()
        if cleaned_data['password_1'] != cleaned_data['password_2']:
            # raise forms.ValidationError('Пароли не совпадают')
            self.add_error('password_1', 'Пароли не совпадают')

    class Meta:
        model = User
        fields = \
            [
                'username',
                'first_name',
                'last_name',
                'email',
            ]


class SurveyForm(forms.Form):
    question = forms.ChoiceField(widget=forms.RadioSelect, choices=())

    def __init__(self, questions, *args, **kwargs):
        super(SurveyForm, self).__init__(*args, **kwargs)
        self.questions = questions
        del self.fields['question']
        for question in questions:
            choices = [(answer.pk, answer.text) for answer in question.answer_set.all()]
            self.fields[f'question{question.pk}'] = forms.ChoiceField(widget=forms.RadioSelect, choices=choices)
            self.fields[f'question{question.pk}'].label = question.text

survey_service/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.views import generic
from .models import Survey, Answer, Color
from .forms import RegistrationUserForm, SurveyForm
from django.contrib.auth import get_user_model


User = get_user_model()


class RegistrationFormView(generic.FormView):
    template_name = 'registration/registration.html'
    form_class = RegistrationUserForm

    def post(self, request, *args, **kwargs):
        form = RegistrationUserForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password_1'])
            user.save()
            login_user = authenticate(request, username=user.username, password=form.cleaned_data['password_1'])
            login(request, login_user)
            return redirect(reverse('survey_service:home'))
        return render(request, self.template_name, context={'form': form})


class HomeView(generic.TemplateView):
    template_name = 'survey_service/home.html'


class SurveyListView(generic.ListView):
    queryset = Survey.objects.all()
    template_name = 'survey_service/all_surveys.html'
    context_object_name = 'surveys'


class SurveyDetailView(LoginRequiredMixin, generic.DetailView):
    queryset = Survey.objects.all()
    template_name = 'survey_service/detail_survey.html'
    context_object_name = 'survey'

    def get_context_data(self, **kwargs):
        questions = self.get_object().question_set.all()
        context = super(SurveyDetailView, self).get_context_data()
        context['form'] = SurveyForm(questions)
        return context

    def post(self, request, *args, **kwargs): # подумать над этой логикой
        survey = self.get_object()
        questions = survey.question_set.all()
        user = request.user
        form = SurveyForm(questions, request.POST)
        if form.is_valid():
            if survey in user.passed_surveys.all():
                return redirect(reverse('survey_service:survey_passed'))
            for value in form.cleaned_data.values():
                answer = Answer.objects.get(pk=int(value))
                if not answer.correct:
                    return redirect(reverse('survey_service:survey_failed'))
            user.currency += survey.point
            user.passed_surveys.add(survey)
            user.save()
            return redirect(reverse('survey_service:survey_passed'))
        return redirect(reverse('survey_service:survey_failed'))


class SurveyPassedView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'survey_service/survey_passed.html'

    def get_context_data(self, **kwargs):
        context = super(SurveyPassedView, self).get_context_data()
        context['point'] = self.request.user.currency
        return context


class SurveyFailedView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'survey_service/survey_failed.html'


class ProfileListView(generic.ListView):
    queryset = User.objects.all()
    context_object_name = 'users'
    template_name = 'survey_service/profile_list.html'
    paginate_by = 20


class ProfileDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = 'survey_service/profile.html'
    model = User
    context_object_name = 'user'

    # def get_context_data(self, **kwargs):
    #     context = super(ProfileDetailView, self).get_context_data()
    #     # context['passed_surveys'] = self.request.user.passed_surveys.all()
    #     context['color'] = self.request.user.color
    #     return context


class ColorListView(LoginRequiredMixin, generic.ListView):
    queryset = Color.objects.all()
    template_name = 'survey_service/colors.html'
    context_object_name = 'colors'


class BuyColorView(LoginRequiredMixin, generic.View):

    def post(self, request, *args, **kwargs):
        user = request.user
        color = get_object_or_404(Color, pk=kwargs['pk'])
        if user.currency >= color.price and color not in user.user_colors.all():
            user.currency -= color.price
            user.color = color.color
            user.user_colors.add(color)
            user.save()
            return redirect(reverse('survey_service:profile', kwargs={'pk': request.user.pk}))
        return redirect(reverse('survey_service:buy_failed'))


class BuyFailedView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'survey_service/buy_failed.html'

templates/survey_service/all_surveys.html
{% extends "base.html" %}


{% block title %}
    Список тестов
{% endblock %}


{% block content %}

    <div style="text-align:center">
        {% for survey in surveys %}
            <a href="{% url 'survey_service:detail_survey' pk=survey.pk %}"><p>{{ survey }}</p></a>
        {% endfor %}
    </div>

    {% if page_obj.has_other_pages %}
        <div class="pagination justify-content-center">
            <a class="page-link" href="?page=1">первая страница</a>
            {% for p in paginator.page_range %}
                {% if p >= page_obj.number|add:-2 and p <= page_obj.number|add:2 %}
                    <a class="page-link" href="?page={{p}}">{{p}}</a>
                {% endif %}
            {% endfor %}
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">последняя страница</a>
        </div>
    {% endif %}

{% endblock %}

templates/survey_service/all_tests.html
{% extends "base.html" %}


{% block title %}
    Список тестов
{% endblock %}


{% block content %}

    <div style="text-align:center">
        {% for test in tests %}
            <a href="{% url 'survey_service:detail_test' pk=test.pk %}"><p>{{ test }}</p></a>
        {% endfor %}
    </div>

    {% if page_obj.has_other_pages %}
        <div class="pagination justify-content-center">
            <a class="page-link" href="?page=1">первая страница</a>
            {% for p in paginator.page_range %}
                {% if p >= page_obj.number|add:-2 and p <= page_obj.number|add:2 %}
                    <a class="page-link" href="?page={{p}}">{{p}}</a>
                {% endif %}
            {% endfor %}
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">последняя страница</a>
        </div>
    {% endif %}

{% endblock %}

templates/survey_service/buy_failed.html
{% extends "base.html" %}


{% block title %}
    Ошибка
{% endblock %}


{% block content %}
    <h1>У вас не хватает денег на покупку или этот цвет у вас уже есть</h1>
{% endblock %}

templates/survey_service/colors.html
{% extends "base.html" %}


{% block title %}
    Магазин
{% endblock %}


{% block content %}
    <div style="text-align:center">
        <table class="table table-dark table-striped" border="1px" align="center" >
            <tr>
                <th>Наименование</th>
                <th>Цена</th>
                <th>

                </th>
            </tr>
            {% for color in colors %}
            <tr>
                <th>
                    {{ color.color }}
                </th>
                <th>
                    {{ color.price }}
                </th>
                <th>
                    <form action="{% url 'survey_service:buy_color' pk=color.pk %}" method="POST">
                        {% csrf_token %}
                        <input type="submit" value="Купить">
                    </form>
                </th>
            </tr>
            {% endfor %}
        </table>
    </div>
{% endblock %}

templates/survey_service/detail_survey.html
{% extends "base.html" %}


{% block title %}
    {{ test.name }}
{% endblock %}


{% block content %}
    <div style="text-align:center">
        <h1>{{ survey.title }}</h1>
        <p>{{ survey.description }}</p>
    </div>
    <div style="text-align:center">
        <form action="." method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Отправить">
        </form>
    </div>

<!--    <div style="text-align:center">-->
<!--        <form action="#" method="POST">-->
<!--            {% csrf_token %}-->
<!--            {% for question in survey.question_set.all %}-->
<!--                <label>{{ question.text }}</label><br>-->
<!--                {% for answer in question.answer_set.all %}-->
<!--                    {{ answer }} <input type="radio" value="answer.text" name="answer.id"><br>-->
<!--                {% endfor %}<br>-->
<!--            {% endfor %}-->
<!--            <input type="submit" value="Отправить">-->
<!--        </form>-->
<!--    </div>-->
{% endblock %}

templates/survey_service/detail_test.html
{% extends "base.html" %}


{% block title %}
    {{ test.name }}
{% endblock %}


{% block content %}
    <div style="text-align:center">
        <h1>{{ test.title }}</h1>
        <p>{{ test.description }}</p>
    </div>
    <div style="text-align:center">
        <form action="." method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Отправить">
        </form>
    </div>

<!--    <div style="text-align:center">-->
<!--        <form action="#" method="POST">-->
<!--            {% csrf_token %}-->
<!--            {% for question in test.question_set.all %}-->
<!--                <label>{{ question.text }}</label><br>-->
<!--                {% for answer in question.answer_set.all %}-->
<!--                    {{ answer }} <input type="radio" value="answer.text" name="answer.id"><br>-->
<!--                {% endfor %}<br>-->
<!--            {% endfor %}-->
<!--            <input type="submit" value="Отправить">-->
<!--        </form>-->
<!--    </div>-->
{% endblock %}

templates/survey_service/home.html
{% extends "base.html" %}


{% block title %}
    Главная страница
{% endblock %}


{% block content %}
        <div>
        <h1>Создать сервис прохождения опросов пользователями на Django.</h1>

            <p>Обязательная часть:</p>
                1. Можно зарегистрироваться и логинится. Наверху показано под каким логином ты зашел.<br>
                2. Тесты и ответы на них создаются динамически через админку.<br>
                3. Список тестов выводится в виде содержания произвольного вида (столбец, таблица, как удобно)<br>

        <br><p>Фронт делается с помощью шаблонизатора Django, СУБД произвольная</p>

        Опция 1.<br>

            1. За прохождение тестов начисляется какое-то количества валюты.<br>
            2. Валюту можно потратить на перекрашивание рамки логина или бэкграунда на странице профиля.<br>
            3. Показывать список пользователей и количество пройденных тестов на отдельной странице, там же показывать цветовую дифференциацию пользователей.<br>

        <br>Опция 2.<br>

            1. Сделать фронт на реакте, в виде SPA или отдельных модулей.


                    Выкатить на github, деплой не обязательно, проверим под режимом разработчика.
    </div>
{% endblock %}

templates/survey_service/profile.html
{% extends "base.html" %}


{% block title %}
    {{ user.username }}
{% endblock %}


{% block content %}
<h1 style="text-align:center">Привет {{ user.username }}!</h1><br>
    <div class="container">
        <div class="row">
            <div class="col">
                <h3>Тесты которые вы прошли:</h3>
                {% for survey in user.passed_surveys.all %}
                    <p>{{ survey }}</p>
                {% endfor %}
            </div>
            <div class="col">
                <h3>Количество баллов:</h3>
                <p>{{ user.currency }}</p>
            </div>
            <div class="col">
                <h3>Ваш цвет:</h3>
                <p>{{ user.color }}</p>
            </div>
        </div>
    </div>
{% endblock %}

templates/survey_service/profile_list.html
{% extends "base.html" %}


{% block title %}
    Пользователи
{% endblock %}


{% block content %}
    <div style="text-align:center">
        <table class="table table-dark table-striped" border="1px" align="center" >
            <tr>
                <th>Имя</th>
                <th>Пройденные тесты</th>
                <th>Цвет</th>
            </tr>
            {% for user in users %}
                <tr>
                    <th>
                        <a href="{% url 'survey_service:profile' pk=user.pk%}">{{ user.username }}</a>
                    </th>
                    <th>
                        {{ user.passed_surveys.count }}
                    </th>
                    <th>
                        {{ user.color }}
                    </th>
                </tr>
            {% endfor %}
        </table>
        {% if page_obj.has_other_pages %}
        <div class="pagination justify-content-center">
            <a class="page-link" href="?page=1">первая страница</a>
            {% for p in paginator.page_range %}
                {% if p >= page_obj.number|add:-2 and p <= page_obj.number|add:2 %}
                    <a class="page-link" href="?page={{p}}">{{p}}</a>
                {% endif %}
            {% endfor %}
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">последняя страница</a>
        </div>
    {% endif %}
    </div>
{% endblock %}

templates/survey_service/survey_failed.html
{% extends "base.html" %}


{% block title %}
    Тест не пройден
{% endblock %}


{% block content %}
    <h1>Вы провалили тест!</h1>
    <p>Вы заработали 0 баллов</p>
{% endblock %}

templates/survey_service/survey_passed.html
{% extends "base.html" %}


{% block title %}
    Тест пройден
{% endblock %}


{% block content %}
        <h1>Тест пройден!</h1>
        <p>У вас {{point}} баллов</p>
        <p>При повторном прохождении теста, баллы начисляться не будут</p>
{% endblock %}

templates/survey_service/test_failed.html
{% extends "base.html" %}


{% block title %}
    Тест не пройден
{% endblock %}


{% block content %}
    <h1>Вы провалили тест!</h1>
    <p>Вы заработали 0 баллов</p>
{% endblock %}

templates/survey_service/test_passed.html
{% extends "base.html" %}


{% block title %}
    Тест пройден
{% endblock %}


{% block content %}
        <h1>Тест пройден!</h1>
        <p>У вас {{point}} баллов</p>
        <p>При повторном прохождении теста, баллы начисляться не будут</p>
{% endblock %}