core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('survey_service.urls')),
    path('', include('django.contrib.auth.urls')),
]

survey_service/urls.py
from django.urls import path
from . import views


app_name = 'survey_service'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('register/', views.RegistrationFormView.as_view(), name='register'),
    path('surveys/', views.SurveyListView.as_view(), name='all_surveys'),
    path('survey/<int:pk>/', views.SurveyDetailView.as_view(), name='detail_survey'),
    path('survey_passed', views.SurveyPassedView.as_view(), name='survey_passed'),
    path('survey_failed', views.SurveyFailedView.as_view(), name='survey_failed'),
    path('profiles', views.ProfileListView.as_view(), name='profile_list'),
    path('profile/<int:pk>/', views.ProfileDetailView.as_view(), name='profile'),
    path('colors/', views.ColorListView.as_view(), name='colors'),
    path('buy_color/<int:pk>/', views.BuyColorView.as_view(), name='buy_color'),
    path('buy_failed/', views.BuyFailedView.as_view(), name='buy_failed'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/">Главная</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
        {% if request.user.is_authenticated %}
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'survey_service:all_surveys' %}">Тесты</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'survey_service:profile' pk=request.user.pk %}">Профиль</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'survey_service:colors'%}">Магазин</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'survey_service:profile_list' %}">Все пользователи</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/logout/">Выход</a>
            </li>
        {% else %}
            <li class="nav-item active">
                <a class="nav-link" href="/register/">Регистрация</a>
            </li>
             <li class="nav-item">
                <a class="nav-link" href="/login/">Вход</a>
            </li>
        {% endif %}
    </ul>
  </div>
  {% if request.user.is_authenticated %}
    <div>
        <span style="color:white">
          Вы зашли как {{ request.user }}
        </span>
    </div>
  {% endif %}
</nav>
    {% block content %}
    {% endblock %}
</body>
</html>